name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-node-version: '16'

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev python3-dev python3-pip python3-setuptools unzip zip lld
          pip3 install --upgrade pip
          pip3 install Cython==0.29.33 buildozer

      - name: Pre-accept SDK Licenses (Решение проблемы с 37.0.0)
        run: |
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb74fa602d3479b19541\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/artifacts@v3
        with:
          name: package
          path: .buildozer/android/platform/build/dists/*/bin/*.apk
